version: '3.8'

services:
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www
      - ./backend/database:/var/www/database
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend:/var/www/frontend
      - ./backend:/var/www/backend
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 