services:
  - type: web
    name: pulse-fitness-backend
    rootDir: backend
    buildCommand: composer install --no-interaction --prefer-dist && php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ${pulse_fitness_db.HOSTNAME}
      - key: DB_PORT
        value: ${pulse_fitness_db.PORT}
      - key: DB_DATABASE
        value: ${pulse_fitness_db.DATABASE}
      - key: DB_USERNAME
        value: ${pulse_fitness_db.USERNAME}
      - key: DB_PASSWORD
        value: ${pulse_fitness_db.PASSWORD}
      - key: LOG_CHANNEL
        value: errorlog
      - key: SANCTUM_STATEFUL_DOMAINS
        value: pulse-fitness.vercel.app
      - key: SESSION_DOMAIN
        value: pulse-fitness-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://pulse-fitness.vercel.app

databases:
  - name: pulse_fitness_db
    databaseName: pulse_fitness
    user: pulse_fitness_user
    plan: free
