[phases.setup]
aptPkgs = ["php", "php-cli", "php-common", "php-mysql", "php-zip", "php-gd", "php-mbstring", "php-curl", "php-xml", "php-bcmath", "unzip"]

[phases.install]
cmds = ["curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer", "composer install --no-interaction --prefer-dist"]

[phases.build]
cmds = ["php artisan key:generate --force", "php artisan config:cache", "php artisan route:cache"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
